[package]
name = "wa1"
version = "0.1.0"
authors = ["theidiotmachine <dinsdt@googlemail.com>"]
edition = "2018"
default-run = "wa1"

[dependencies]
ress = { path = "../ress" }
ast = { path = "../ast" }
parser = { path = "../parser" }
writer = { path = "../writer" }
clap = "~2.33.0"
